name: Build and Release Mineconomy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 서브모듈을 재귀적으로 체크아웃하여 최신 소스 가져오기

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'


      - name: Generate build.gradle for Mineconomy-Core
        run: |
          echo "plugins { id 'java' }" > Mineconomy-Core/build.gradle

      - name: Build Mineconomy-Core
        run: |
          cd Mineconomy-Core
          gradle wrapper  # Gradle Wrapper 동적 생성
          ./gradlew build
          cp build/libs/*.jar ../release  # 최종 빌드된 JAR 파일을 release 폴더에 복사

      - name: Build Dynamic_Graph
        run: |
          cd Dynamic_Graph
          gradle wrapper  # Gradle Wrapper 동적 생성
          ./gradlew build
          cp build/libs/*.jar ../release  # 최종 빌드된 JAR 파일을 release 폴더에 복사

      - name: Package Resource Pack
        run: |
          mkdir -p release
          cp Resource_Pack/*.zip release/  # 리소스 팩 압축 파일을 release 폴더에 복사

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            자동 생성된 릴리즈입니다.
          draft: false
          prerelease: false
          artifacts: |
            release/*.jar
            release/*.zip
