name: Release Automation

on:
  push:
    tags:
      - 'v*.*.*'  # 태그를 통해 릴리즈를 트리거. 예: v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Package Release Files
        run: |
          mkdir release
          cp -r build/libs/* release/  # 빌드된 JAR 파일 복사
          cp -r path/to/Dynamic_Graph/build/libs/* release/  # 그래프 모듈 복사
          cp -r path/to/Resource_Pack/*.zip release/  # 리소스팩 압축 파일 복사

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release
          draft: false
          prerelease: false
          artifacts: |
            release/*.jar
            release/*.zip
